# ----------------------------------------
# Created on: Wed Aug 13 15:02:06 2025
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work led_diaplay_top_tb
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
