# ----------------------------------------
# Created on: Wed Aug 13 15:02:06 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/led_display/new/for_lab_v2/hc595_ctrl.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/led_display/new/for_lab_v2/led_display_seg_ctrl.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/led_display/new/for_lab_v2/led_display_top.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/led_display/new/for_lab_v2/tb.v" 

# ----------------------------------------
