# ----------------------------------------
# Created on: Wed Oct 18 10:28:30 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work tb_key_filter
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
