# ----------------------------------------
# Created on: Wed Oct 18 10:28:30 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"D:/pango_fire/PG2L100H/10_key_filter/rtl/key_filter.v" \
"D:/pango_fire/PG2L100H/10_key_filter/sim/tb_key_filter.v" 

# ----------------------------------------
