#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Aug 20 11:43:19 2025

add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/matrix_key.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/matrix_key_top.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/matrix_key_trigger.v"
remove_design -verilog "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/matrix_key_trigger.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/hc595_ctrl.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/led_display_seg_ctrl.v"
add_constraint "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/04_matrix_key/rtl/IO.fdc"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -system_verilog -top_module matrix_key_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
