# ----------------------------------------
# Created on: Mon May 19 22:05:44 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/usim"
vmap  adc_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/bcd2ascii.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/bin2bcd.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/cymometer.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/frequency_meter.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/led_display_driver.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/pulse_gen.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/rtl/led_display_selector.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/prj/frequency_meter/ipcore/PLL/PLL.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/13_frequency_meter/sim/frequency_meter_tb.sv" 

# ----------------------------------------
