# ----------------------------------------
# Created on: Fri Aug 22 01:10:05 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/usim"
vmap  adc_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/adc_e2"
vmap  ddc_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/ddc_e2"
vmap  dll_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/dll_e2"
vmap  hsstlp_lane "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/hsstlp_lane"
vmap  hsstlp_pll "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/hsstlp_pll"
vmap  iolhr_dft "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/iolhr_dft"
vmap  ipal_e1 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/ipal_e1"
vmap  ipal_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/ipal_e2"
vmap  iserdes_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/iserdes_e2"
vmap  oserdes_e2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/oserdes_e2"
vmap  pciegen2 "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/sim/pciegen2"
vlog -work work   \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/rtl/hc595_ctrl.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/rtl/led.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/rtl/led_display_seg_ctrl.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/show_1_led_matrix/rtl/tb.v" 

# ----------------------------------------
