# ----------------------------------------
# Created on: Tue May 13 20:50:40 2025
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work hdmi_top_tb
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
