#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Fri May  9 13:19:23 2025

add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_loop.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/iic_dri.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/ms7210_ctl.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/ms7210_ctrl_iic_top.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/vga_ctrl.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/vga_pic.v"
add_design E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/prj/hdmi_colorbar/ipcore/PLL/PLL.idf
add_constraint "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_loop.fdc"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_loop
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -verilog "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_loop.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_top.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_constraint  -logic -fdc "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_loop.fdc"
add_constraint "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_out.fdc"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_simulation "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/sim/hdmi_top_tb.v"
remove_design -verilog "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/vga_pic.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/SD/sd_ctrl.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/SD/sd_init.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/SD/sd_read.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/SD/sd_write.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/axi_ddr3_rw/axi_ctrl.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/axi_ddr3_rw/axi_ddr_top.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/axi_ddr3_rw/axi_master_read.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/axi_ddr3_rw/axi_master_write.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/prj/hdmi_colorbar/ipcore/rd_fifo/rd_fifo.idf"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/prj/hdmi_colorbar/ipcore/wr_fifo/wr_fifo.idf"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/prj/hdmi_colorbar/ipcore/ddr3_test/ddr3_test.idf"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/rtl/data_rd_ctrl.v"
add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/ISP_lab/06_hdmi/prj/hdmi_colorbar/ipcore/PLL_2/PLL_2.idf"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
pnr 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
