# ----------------------------------------
# Created on: Tue May 13 20:50:40 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/iic_dri.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/ms7210_ctl.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/ms7210_ctrl_iic_top.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/vga_ctrl.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/vga_pic.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/rtl/hdmi_top.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/prj/hdmi_colorbar/ipcore/PLL/PLL.v" \
"E:/JiChuang_2025/PDS_Project/axi_udp_ddr/LAB/hdmi/sim/hdmi_top_tb.v" 

# ----------------------------------------
