#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Tue May 20 13:58:02 2025

add_design "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/01_water_led/rtl/waterled_top.v"
add_constraint "E:/JiChuang_2025/PDS_Project/axi_udp_ddr/pangu_-remote_-lab/examination/01_water_led/rtl/IO.fdc"
