../../../DDR3/*.v
../../../UDP/*.v
../../../AXI4/slave_axi_async.v
../../../DDR3/sim_file/ddr3.v

../udp_axi_ddr_tb_top.v

../../../IPCORE/fifo_ddr3_read/rtl/ipm2l_fifo_ctrl_v1_1_fifo_ddr3_read.v
../../../IPCORE/fifo_ddr3_read/rtl/ipm2l_sdpram_v1_10_fifo_ddr3_read.v
../../../IPCORE/fifo_ddr3_read/rtl/ipm2l_fifo_v1_10_fifo_ddr3_read.v
../../../IPCORE/fifo_ddr3_read/fifo_ddr3_read.v

../../../IPCORE/fifo_ddr3_write/rtl/ipm2l_fifo_ctrl_v1_1_fifo_ddr3_write.v 
../../../IPCORE/fifo_ddr3_write/rtl/ipm2l_sdpram_v1_10_fifo_ddr3_write.v
../../../IPCORE/fifo_ddr3_write/rtl/ipm2l_fifo_v1_10_fifo_ddr3_write.v
../../../IPCORE/fifo_ddr3_write/fifo_ddr3_write.v

../../../IPCORE/fifo_ddr3_write_strb/rtl/ipm2l_fifo_ctrl_v1_1_fifo_ddr3_write_strb.v
../../../IPCORE/fifo_ddr3_write_strb/rtl/ipm2l_sdpram_v1_10_fifo_ddr3_write_strb.v
../../../IPCORE/fifo_ddr3_write_strb/rtl/ipm2l_fifo_v1_10_fifo_ddr3_write_strb.v
../../../IPCORE/fifo_ddr3_write_strb/fifo_ddr3_write_strb.v

../../../IPCORE/axi_ddr3/sim_lib/ips2l_rst_sync_v1_3.v
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_wrlvl_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_wrcal_v1_7.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_wdata_path_adj_v1_10.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_upcal_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_training_ctrl_v1_11.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_slice_rddata_align_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_reset_ctrl_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_rdcal_v1_10.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_main_ctrl_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_init_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_info_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_gatecal_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_gate_update_ctrl_v1_11.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_eyecal_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_drift_ctrl_v1_11.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_dqsi_rdel_cal_v1_15.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_dqs_rddata_align_v1_12.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_dqs_gate_coarse_cal_v1_12.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_dll_update_ctrl_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_dfi_v1_3.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_gpll_phase_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_data_slice_wrlvl_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_data_slice_wrcal_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_data_slice_v1_15.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_data_slice_dqs_gate_cal_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_cpd_ctrl_v1_3.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_cpd_lock_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_control_path_adj_v1_10.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_calib_top_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_calib_mux_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_rst_debounce_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_rst_clk_phase_adj_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/ddrphy/ips2l_ddrphy_check_ppll_out_sync_point_v1_14.vp
../../../IPCORE/axi_ddr3/sim_lib/pll/ips2l_ddrphy_gpll_v1_3.v
../../../IPCORE/axi_ddr3/sim_lib/pll/ips2l_ddrphy_ppll_v1_0.v
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_bresp_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_cmd_align_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_cmd_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_bresp_buf_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_buf_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_channel_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_cmd_arb_v1_5a.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_dec_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_mc_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_rdata_align_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_rdata_arrange_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_axi_wdata_align_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_rddata_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_rdata_align_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_wdata_align_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_wdata_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_ui_axi_v1_5a.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/axi/ips2l_mcdq_reg_fifo2_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/distributed_fifo/ips2l_distributed_fifo_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/distributed_fifo/rtl/ips2l_distributed_fifo_ctr_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/distributed_fifo/rtl/ips2l_distributed_fifo_v1_0_distributed_fifo_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/distributed_fifo/rtl/ips2l_distributed_sdpram_v1_0_distributed_fifo_v1_0.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_apb_cross_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_calib_delay_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_cfg_apb_v1_5a.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcd_bm_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcd_rowaddr_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcd_sm_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcd_top_v1_8.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcp_back_ctrl_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcp_buf_v1_8b.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcp_out_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dcp_top_v1_8b.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_dfi_v1_7a.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_lp_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_mac_top_v1_8b.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_mpr_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_mrs_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_prefetch_fifo_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_rdatapath_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_wdatapath_v1_8.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_wdp_align_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/ips2l_mcdq_wdp_dcp_v1_6.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_com_timing_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_tfaw_timing_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_tfaw_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_timing_act_pass_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_timing_act2wr_pass_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_timing_pre_pass_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_timing_rd_pass_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_timing_ref_pass_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_timing_wr_pass_v1_5.vp
../../../IPCORE/axi_ddr3/sim_lib/mcdq/mac/syn_mod/ips2l_mcdq_trc_timing_v1_5.vp
../../../IPCORE/axi_ddr3/axi_ddr3.v
../../../IPCORE/axi_ddr3/axi_ddr3_ddrphy_top.v
../../../IPCORE/axi_ddr3/rtl/mcdq/axi_ddr3_mcdq_wrapper_v1_9.v
../../../IPCORE/axi_ddr3/rtl/ddrphy/axi_ddr3_slice_top_v1_15.v

../../../IPCORE/async_addr_fifo/rtl/ipm2l_fifo_ctrl_v1_1_async_addr_fifo.v
../../../IPCORE/async_addr_fifo/rtl/ipm2l_sdpram_v1_10_async_addr_fifo.v
../../../IPCORE/async_addr_fifo/rtl/ipm2l_fifo_v1_10_async_addr_fifo.v
../../../IPCORE/async_addr_fifo/async_addr_fifo.v

../../../IPCORE/async_wr_data_fifo/rtl/ipm2l_fifo_ctrl_v1_1_async_wr_data_fifo.v
../../../IPCORE/async_wr_data_fifo/rtl/ipm2l_sdpram_v1_10_async_wr_data_fifo.v
../../../IPCORE/async_wr_data_fifo/rtl/ipm2l_fifo_v1_10_async_wr_data_fifo.v
../../../IPCORE/async_wr_data_fifo/async_wr_data_fifo.v

../../../IPCORE/async_rd_data_fifo/rtl/ipm2l_fifo_ctrl_v1_1_async_rd_data_fifo.v
../../../IPCORE/async_rd_data_fifo/rtl/ipm2l_sdpram_v1_10_async_rd_data_fifo.v
../../../IPCORE/async_rd_data_fifo/rtl/ipm2l_fifo_v1_10_async_rd_data_fifo.v
../../../IPCORE/async_rd_data_fifo/async_rd_data_fifo.v 

../../../IPCORE/udp_fifo_rd/rtl/ipm2l_fifo_ctrl_v1_1_udp_fifo_rd.v
../../../IPCORE/udp_fifo_rd/rtl/ipm2l_sdpram_v1_10_udp_fifo_rd.v
../../../IPCORE/udp_fifo_rd/rtl/ipm2l_fifo_v1_10_udp_fifo_rd.v
../../../IPCORE/udp_fifo_rd/udp_fifo_rd.v

../../../IPCORE/udp_fifo_wr/rtl/ipm2l_fifo_ctrl_v1_1_udp_fifo_wr.v
../../../IPCORE/udp_fifo_wr/rtl/ipm2l_sdpram_v1_10_udp_fifo_wr.v
../../../IPCORE/udp_fifo_wr/rtl/ipm2l_fifo_v1_10_udp_fifo_wr.v
../../../IPCORE/udp_fifo_wr/udp_fifo_wr.v 

../../../IPCORE/clk_phase/clk_phase.v 

+incdir+../../../DDR3/sim_file
+define+IPS_DDR_SPEEDUP_SIM  
+define+RTL_SIM 
+define+den4096Mb   
+define+x16         
+define+sg25E       
-sv