# ----------------------------------------
# Created on: Fri Mar 21 11:36:52 2025
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work -L usim -L adc_e2 -L ddc_e2 -L dll_e2 -L hsstlp_lane -L hsstlp_pll -L iolhr_dft -L ipal_e1 -L ipal_e2 -L iserdes_e2 -L oserdes_e2 -L pciegen2 udp_axi_ddr_top usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
