# ----------------------------------------
# Created on: Sat Mar  8 18:31:55 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/usim"
vmap  adc_e2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/01_led/pds_prj/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/rtl/dds.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/rtl/key_control.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/rtl/key_filter.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/rtl/top_dds.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/pds_prj/ipcore/rom_wave/rtl/ipm2l_rom_v1_8_rom_wave.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/pds_prj/ipcore/rom_wave/rtl/ipm2l_spram_v1_8_rom_wave.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/pds_prj/ipcore/rom_wave/rom_wave.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/sim/tb_dds.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/sim/tb_key_control.v" \
"E:/JiChuang_2025/ebf_pg2l100h_tutorial_code_20231227/18_dds/sim/tb_top_dds.v" 

# ----------------------------------------
